// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/worker/worker.proto

package worker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkerRequest struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRequest) Reset()         { *m = WorkerRequest{} }
func (m *WorkerRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerRequest) ProtoMessage()    {}
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f3991b04f0a1061, []int{0}
}

func (m *WorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRequest.Unmarshal(m, b)
}
func (m *WorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRequest.Marshal(b, m, deterministic)
}
func (m *WorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRequest.Merge(m, src)
}
func (m *WorkerRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerRequest.Size(m)
}
func (m *WorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRequest proto.InternalMessageInfo

func (m *WorkerRequest) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type WorkerResponse struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerResponse) Reset()         { *m = WorkerResponse{} }
func (m *WorkerResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerResponse) ProtoMessage()    {}
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f3991b04f0a1061, []int{1}
}

func (m *WorkerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerResponse.Unmarshal(m, b)
}
func (m *WorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerResponse.Marshal(b, m, deterministic)
}
func (m *WorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerResponse.Merge(m, src)
}
func (m *WorkerResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerResponse.Size(m)
}
func (m *WorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerResponse proto.InternalMessageInfo

func (m *WorkerResponse) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkerRequest)(nil), "v1.worker.WorkerRequest")
	proto.RegisterType((*WorkerResponse)(nil), "v1.worker.WorkerResponse")
}

func init() {
	proto.RegisterFile("protos/v1/worker/worker.proto", fileDescriptor_8f3991b04f0a1061)
}

var fileDescriptor_8f3991b04f0a1061 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x33, 0xd4, 0x2f, 0xcf, 0x2f, 0xca, 0x4e, 0x2d, 0x82, 0x52, 0x7a, 0x60,
	0x71, 0x21, 0xce, 0x32, 0x43, 0x3d, 0x88, 0x80, 0x92, 0x22, 0x17, 0x6f, 0x38, 0x98, 0x15, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc0, 0xc5, 0x5c, 0x94, 0x5a, 0x28, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0x29, 0x71, 0xf1, 0xc1, 0x94, 0x14, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x42, 0xd4, 0x14, 0x23, 0xd4, 0x14, 0x1b, 0x9d, 0x66, 0xe4, 0x62, 0x83, 0x28, 0x12, 0x72,
	0xe3, 0xe2, 0x77, 0x4f, 0x2d, 0x81, 0x70, 0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0x24, 0xf4,
	0xe0, 0x16, 0xea, 0xa1, 0xd8, 0x26, 0x25, 0x89, 0x45, 0x06, 0x6a, 0x89, 0x0d, 0x17, 0x2b, 0x50,
	0x7b, 0x51, 0x09, 0x79, 0xba, 0xad, 0xb9, 0x58, 0x82, 0x4b, 0xf2, 0x0b, 0xc8, 0xd2, 0xec, 0x64,
	0x1a, 0x65, 0x9c, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x98, 0x9c,
	0x5c, 0x9a, 0x9d, 0x97, 0x5f, 0xa1, 0x0f, 0x22, 0x1c, 0x4b, 0x4b, 0xf2, 0x03, 0xf2, 0x73, 0x32,
	0x93, 0x2b, 0xf5, 0xd1, 0xc3, 0x38, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x9c, 0x83, 0x4c, 0x27, 0x7e, 0x01, 0x00, 0x00,
}
