apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-engine-config
data:
  conf.yaml: |-
    application:
      name: discovery-engine
      network:
        operation-mode: 1                         # 1: cronjob | 2: one-time-job
        cron-job-time-interval: "0h0m10s"         # format: XhYmZs
        operation-trigger: 5
        network-log-from: "kubearmor"             # db|hubble|feed-consumer|kubearmor
        network-log-file: "./flow.json"           # file path
        network-policy-to: "db"                   # db, file
        network-policy-dir: "./"
        namespace-filter:
        - "!kube-system"
      system:
        operation-mode: 1                         # 1: cronjob | 2: one-time-job
        cron-job-time-interval: "0h0m10s"         # format: XhYmZs
        operation-trigger: 5
        system-log-from: "kubearmor"              # db|kubearmor|feed-consumer
        system-log-file: "./log.json"             # file path
        system-policy-to: "db"                    # db, file
        system-policy-dir: "./"
        deprecate-old-mode: true
        namespace-filter:
        - "!kube-system"
        fromsource-filter:
        - "knoxAutoPolicy"
        
      admission-controller:
        generic-policy-list:
        - "restrict-deprecated-registry"
        - "prevent-cr8escape"
        - "check-kernel-version"
        - "restrict-ingress-defaultbackend"
        - "restrict-nginx-ingress-annotations"
        - "restrict-ingress-paths"
        - "prevent-naked-pods"
        - "restrict-wildcard-verbs"
        - "restrict-wildcard-resources"
        - "require-requests-limits"
        - "require-pod-probes"
        - "drop-cap-net-raw"

      cluster:
        cluster-info-from: "k8sclient"            # k8sclient|accuknox

    observability: 
      enable: true
      cron-job-time-interval: "0h0m10s"         # format: XhYmZs
      dbname: ./accuknox-obs.db
      system-observability: true
      network-observability: false
      write-logs-to-db: false
      summary-jobs:
        publisher: true
        write-summary-to-db: true
        cron-interval: "0h1m00s"

    database:
      driver: sqlite3
      host: mysql.explorer.svc.cluster.local
      port: 3306
      user: root
      password: password
      dbname: discovery-engine
      table-configuration: auto_policy_config
      table-network-log: network_log
      table-network-policy: network_policy
      table-system-log: system_log
      table-system-policy: system_policy

    feed-consumer:
      driver: "pulsar"
      servers:
        - "pulsar-proxy.accuknox-dev-pulsar.svc.cluster.local:6650"
      topic: 
        cilium: "persistent://accuknox/datapipeline/ciliumalertsflowv1"
        kubearmor: "persistent://accuknox/datapipeline/kubearmoralertsflowv1"
      encryption:
        enable: false
        ca-cert: /kafka-ssl/ca.pem 
      auth:
        enable: false
        cert: /kafka-ssl/user.cert.pem
        key: /kafka-ssl/user.key.pem

    logging:
      level: "INFO"

    # kubectl -n kube-system port-forward service/hubble-relay --address 0.0.0.0 --address :: 4245:80

    cilium-hubble:
      url: hubble-relay.kube-system.svc.cluster.local
      port: 80

    kubearmor:
      url: kubearmor.kube-system.svc.cluster.local
      port: 32767

    # Recommended policies configuration

    recommend:
      operation-mode: 1                       # 1: cronjob | 2: one-time-job
      cron-job-time-interval: "1h0m00s"       # format: XhYmZs
      recommend-host-policy: true
      template-version: ""
      admission-controller-policy: false

    # license

    license:
      enabled: false
      validate: "user-id"

    dsp:
      auto-deploy-dsp: false