// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: v1/observability/observability.proto

package observability

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObservabilityClient is the client API for Observability service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObservabilityClient interface {
	SysObservabilityData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error)
}

type observabilityClient struct {
	cc grpc.ClientConnInterface
}

func NewObservabilityClient(cc grpc.ClientConnInterface) ObservabilityClient {
	return &observabilityClient{cc}
}

func (c *observabilityClient) SysObservabilityData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.observability.Observability/SysObservabilityData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservabilityServer is the server API for Observability service.
// All implementations must embed UnimplementedObservabilityServer
// for forward compatibility
type ObservabilityServer interface {
	SysObservabilityData(context.Context, *Data) (*Response, error)
	mustEmbedUnimplementedObservabilityServer()
}

// UnimplementedObservabilityServer must be embedded to have forward compatible implementations.
type UnimplementedObservabilityServer struct {
}

func (UnimplementedObservabilityServer) SysObservabilityData(context.Context, *Data) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysObservabilityData not implemented")
}
func (UnimplementedObservabilityServer) mustEmbedUnimplementedObservabilityServer() {}

// UnsafeObservabilityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservabilityServer will
// result in compilation errors.
type UnsafeObservabilityServer interface {
	mustEmbedUnimplementedObservabilityServer()
}

func RegisterObservabilityServer(s grpc.ServiceRegistrar, srv ObservabilityServer) {
	s.RegisterService(&Observability_ServiceDesc, srv)
}

func _Observability_SysObservabilityData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservabilityServer).SysObservabilityData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.observability.Observability/SysObservabilityData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservabilityServer).SysObservabilityData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// Observability_ServiceDesc is the grpc.ServiceDesc for Observability service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Observability_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.observability.Observability",
	HandlerType: (*ObservabilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysObservabilityData",
			Handler:    _Observability_SysObservabilityData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/observability/observability.proto",
}
