// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigRequest struct {
	ConfigName           string   `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Config               *Config  `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{0}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *ConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type ConfigResponse struct {
	Msg                  string    `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Config               []*Config `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{1}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ConfigResponse) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type ConfigDB struct {
	DbDriver              string   `protobuf:"bytes,1,opt,name=db_driver,json=dbDriver,proto3" json:"db_driver,omitempty"`
	DbHost                string   `protobuf:"bytes,2,opt,name=db_host,json=dbHost,proto3" json:"db_host,omitempty"`
	DbPort                string   `protobuf:"bytes,3,opt,name=db_port,json=dbPort,proto3" json:"db_port,omitempty"`
	DbUser                string   `protobuf:"bytes,4,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPass                string   `protobuf:"bytes,5,opt,name=db_pass,json=dbPass,proto3" json:"db_pass,omitempty"`
	DbName                string   `protobuf:"bytes,6,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	TableNetworkFlow      string   `protobuf:"bytes,7,opt,name=table_network_flow,json=tableNetworkFlow,proto3" json:"table_network_flow,omitempty"`
	TableDiscoveredPolicy string   `protobuf:"bytes,8,opt,name=table_discovered_policy,json=tableDiscoveredPolicy,proto3" json:"table_discovered_policy,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ConfigDB) Reset()         { *m = ConfigDB{} }
func (m *ConfigDB) String() string { return proto.CompactTextString(m) }
func (*ConfigDB) ProtoMessage()    {}
func (*ConfigDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{2}
}

func (m *ConfigDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigDB.Unmarshal(m, b)
}
func (m *ConfigDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigDB.Marshal(b, m, deterministic)
}
func (m *ConfigDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigDB.Merge(m, src)
}
func (m *ConfigDB) XXX_Size() int {
	return xxx_messageInfo_ConfigDB.Size(m)
}
func (m *ConfigDB) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigDB.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigDB proto.InternalMessageInfo

func (m *ConfigDB) GetDbDriver() string {
	if m != nil {
		return m.DbDriver
	}
	return ""
}

func (m *ConfigDB) GetDbHost() string {
	if m != nil {
		return m.DbHost
	}
	return ""
}

func (m *ConfigDB) GetDbPort() string {
	if m != nil {
		return m.DbPort
	}
	return ""
}

func (m *ConfigDB) GetDbUser() string {
	if m != nil {
		return m.DbUser
	}
	return ""
}

func (m *ConfigDB) GetDbPass() string {
	if m != nil {
		return m.DbPass
	}
	return ""
}

func (m *ConfigDB) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ConfigDB) GetTableNetworkFlow() string {
	if m != nil {
		return m.TableNetworkFlow
	}
	return ""
}

func (m *ConfigDB) GetTableDiscoveredPolicy() string {
	if m != nil {
		return m.TableDiscoveredPolicy
	}
	return ""
}

type ConfigCiliumHubble struct {
	HubbleUrl            string   `protobuf:"bytes,1,opt,name=hubble_url,json=hubbleUrl,proto3" json:"hubble_url,omitempty"`
	HubblePort           string   `protobuf:"bytes,2,opt,name=hubble_port,json=hubblePort,proto3" json:"hubble_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigCiliumHubble) Reset()         { *m = ConfigCiliumHubble{} }
func (m *ConfigCiliumHubble) String() string { return proto.CompactTextString(m) }
func (*ConfigCiliumHubble) ProtoMessage()    {}
func (*ConfigCiliumHubble) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{3}
}

func (m *ConfigCiliumHubble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigCiliumHubble.Unmarshal(m, b)
}
func (m *ConfigCiliumHubble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigCiliumHubble.Marshal(b, m, deterministic)
}
func (m *ConfigCiliumHubble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigCiliumHubble.Merge(m, src)
}
func (m *ConfigCiliumHubble) XXX_Size() int {
	return xxx_messageInfo_ConfigCiliumHubble.Size(m)
}
func (m *ConfigCiliumHubble) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigCiliumHubble.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigCiliumHubble proto.InternalMessageInfo

func (m *ConfigCiliumHubble) GetHubbleUrl() string {
	if m != nil {
		return m.HubbleUrl
	}
	return ""
}

func (m *ConfigCiliumHubble) GetHubblePort() string {
	if m != nil {
		return m.HubblePort
	}
	return ""
}

type IgnoringFlows struct {
	IgSelectorNamespace  string   `protobuf:"bytes,1,opt,name=ig_selector_namespace,json=igSelectorNamespace,proto3" json:"ig_selector_namespace,omitempty"`
	IgSelectorLabels     []string `protobuf:"bytes,2,rep,name=ig_selector_labels,json=igSelectorLabels,proto3" json:"ig_selector_labels,omitempty"`
	IgTargetNamespace    string   `protobuf:"bytes,3,opt,name=ig_target_namespace,json=igTargetNamespace,proto3" json:"ig_target_namespace,omitempty"`
	IgTargetLabels       []string `protobuf:"bytes,4,rep,name=ig_target_labels,json=igTargetLabels,proto3" json:"ig_target_labels,omitempty"`
	IgProtocol           string   `protobuf:"bytes,5,opt,name=ig_protocol,json=igProtocol,proto3" json:"ig_protocol,omitempty"`
	IgPortNumber         string   `protobuf:"bytes,6,opt,name=ig_port_number,json=igPortNumber,proto3" json:"ig_port_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgnoringFlows) Reset()         { *m = IgnoringFlows{} }
func (m *IgnoringFlows) String() string { return proto.CompactTextString(m) }
func (*IgnoringFlows) ProtoMessage()    {}
func (*IgnoringFlows) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{4}
}

func (m *IgnoringFlows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgnoringFlows.Unmarshal(m, b)
}
func (m *IgnoringFlows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgnoringFlows.Marshal(b, m, deterministic)
}
func (m *IgnoringFlows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgnoringFlows.Merge(m, src)
}
func (m *IgnoringFlows) XXX_Size() int {
	return xxx_messageInfo_IgnoringFlows.Size(m)
}
func (m *IgnoringFlows) XXX_DiscardUnknown() {
	xxx_messageInfo_IgnoringFlows.DiscardUnknown(m)
}

var xxx_messageInfo_IgnoringFlows proto.InternalMessageInfo

func (m *IgnoringFlows) GetIgSelectorNamespace() string {
	if m != nil {
		return m.IgSelectorNamespace
	}
	return ""
}

func (m *IgnoringFlows) GetIgSelectorLabels() []string {
	if m != nil {
		return m.IgSelectorLabels
	}
	return nil
}

func (m *IgnoringFlows) GetIgTargetNamespace() string {
	if m != nil {
		return m.IgTargetNamespace
	}
	return ""
}

func (m *IgnoringFlows) GetIgTargetLabels() []string {
	if m != nil {
		return m.IgTargetLabels
	}
	return nil
}

func (m *IgnoringFlows) GetIgProtocol() string {
	if m != nil {
		return m.IgProtocol
	}
	return ""
}

func (m *IgnoringFlows) GetIgPortNumber() string {
	if m != nil {
		return m.IgPortNumber
	}
	return ""
}

type Config struct {
	ConfigName              string              `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Status                  int32               `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ConfigDb                *ConfigDB           `protobuf:"bytes,3,opt,name=config_db,json=configDb,proto3" json:"config_db,omitempty"`
	ConfigCiliumHubble      *ConfigCiliumHubble `protobuf:"bytes,4,opt,name=config_cilium_hubble,json=configCiliumHubble,proto3" json:"config_cilium_hubble,omitempty"`
	OperationMode           int32               `protobuf:"varint,5,opt,name=operation_mode,json=operationMode,proto3" json:"operation_mode,omitempty"`
	CronjobTimeInterval     string              `protobuf:"bytes,6,opt,name=cronjob_time_interval,json=cronjobTimeInterval,proto3" json:"cronjob_time_interval,omitempty"`
	OneTimeJobTimeSelection string              `protobuf:"bytes,7,opt,name=one_time_job_time_selection,json=oneTimeJobTimeSelection,proto3" json:"one_time_job_time_selection,omitempty"`
	NetworkLogFrom          string              `protobuf:"bytes,8,opt,name=network_log_from,json=networkLogFrom,proto3" json:"network_log_from,omitempty"`
	DiscoveredPolicyTo      string              `protobuf:"bytes,9,opt,name=discovered_policy_to,json=discoveredPolicyTo,proto3" json:"discovered_policy_to,omitempty"`
	PolicyDir               string              `protobuf:"bytes,10,opt,name=policy_dir,json=policyDir,proto3" json:"policy_dir,omitempty"`
	DiscoveryPolicyTypes    int32               `protobuf:"varint,11,opt,name=discovery_policy_types,json=discoveryPolicyTypes,proto3" json:"discovery_policy_types,omitempty"`
	DiscoveryRuleTypes      int32               `protobuf:"varint,12,opt,name=discovery_rule_types,json=discoveryRuleTypes,proto3" json:"discovery_rule_types,omitempty"`
	CidrBits                int32               `protobuf:"varint,13,opt,name=cidr_bits,json=cidrBits,proto3" json:"cidr_bits,omitempty"`
	IgnoringFlows           []*IgnoringFlows    `protobuf:"bytes,14,rep,name=ignoring_flows,json=ignoringFlows,proto3" json:"ignoring_flows,omitempty"`
	L3AggregationLevel      int32               `protobuf:"varint,15,opt,name=l3_aggregation_level,json=l3AggregationLevel,proto3" json:"l3_aggregation_level,omitempty"`
	L4Compression           int32               `protobuf:"varint,16,opt,name=l4_compression,json=l4Compression,proto3" json:"l4_compression,omitempty"`
	L7AggregationLevel      int32               `protobuf:"varint,17,opt,name=l7_aggregation_level,json=l7AggregationLevel,proto3" json:"l7_aggregation_level,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}            `json:"-"`
	XXX_unrecognized        []byte              `json:"-"`
	XXX_sizecache           int32               `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49a8d8549545cb5, []int{5}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *Config) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Config) GetConfigDb() *ConfigDB {
	if m != nil {
		return m.ConfigDb
	}
	return nil
}

func (m *Config) GetConfigCiliumHubble() *ConfigCiliumHubble {
	if m != nil {
		return m.ConfigCiliumHubble
	}
	return nil
}

func (m *Config) GetOperationMode() int32 {
	if m != nil {
		return m.OperationMode
	}
	return 0
}

func (m *Config) GetCronjobTimeInterval() string {
	if m != nil {
		return m.CronjobTimeInterval
	}
	return ""
}

func (m *Config) GetOneTimeJobTimeSelection() string {
	if m != nil {
		return m.OneTimeJobTimeSelection
	}
	return ""
}

func (m *Config) GetNetworkLogFrom() string {
	if m != nil {
		return m.NetworkLogFrom
	}
	return ""
}

func (m *Config) GetDiscoveredPolicyTo() string {
	if m != nil {
		return m.DiscoveredPolicyTo
	}
	return ""
}

func (m *Config) GetPolicyDir() string {
	if m != nil {
		return m.PolicyDir
	}
	return ""
}

func (m *Config) GetDiscoveryPolicyTypes() int32 {
	if m != nil {
		return m.DiscoveryPolicyTypes
	}
	return 0
}

func (m *Config) GetDiscoveryRuleTypes() int32 {
	if m != nil {
		return m.DiscoveryRuleTypes
	}
	return 0
}

func (m *Config) GetCidrBits() int32 {
	if m != nil {
		return m.CidrBits
	}
	return 0
}

func (m *Config) GetIgnoringFlows() []*IgnoringFlows {
	if m != nil {
		return m.IgnoringFlows
	}
	return nil
}

func (m *Config) GetL3AggregationLevel() int32 {
	if m != nil {
		return m.L3AggregationLevel
	}
	return 0
}

func (m *Config) GetL4Compression() int32 {
	if m != nil {
		return m.L4Compression
	}
	return 0
}

func (m *Config) GetL7AggregationLevel() int32 {
	if m != nil {
		return m.L7AggregationLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigRequest)(nil), "v1.config.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "v1.config.ConfigResponse")
	proto.RegisterType((*ConfigDB)(nil), "v1.config.ConfigDB")
	proto.RegisterType((*ConfigCiliumHubble)(nil), "v1.config.ConfigCiliumHubble")
	proto.RegisterType((*IgnoringFlows)(nil), "v1.config.IgnoringFlows")
	proto.RegisterType((*Config)(nil), "v1.config.Config")
}

func init() {
	proto.RegisterFile("protos/v1/config/config.proto", fileDescriptor_a49a8d8549545cb5)
}

var fileDescriptor_a49a8d8549545cb5 = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x56, 0x93, 0xc6, 0xb5, 0xc7, 0xb5, 0x49, 0x26, 0x6d, 0xb3, 0x50, 0x45, 0x54, 0x16, 0x48,
	0x45, 0x42, 0x36, 0x4d, 0x02, 0x95, 0x50, 0x11, 0x4a, 0x62, 0x95, 0x16, 0xa5, 0x21, 0x72, 0x92,
	0x1b, 0xb8, 0x18, 0xed, 0xcf, 0x64, 0x3b, 0x74, 0xbc, 0xb3, 0xcc, 0xcc, 0xba, 0xf8, 0x15, 0xb8,
	0xe4, 0x2d, 0x78, 0x0c, 0xde, 0x8c, 0x33, 0x67, 0x66, 0xd7, 0x6e, 0x1c, 0x51, 0x29, 0x37, 0xc9,
	0xce, 0xf7, 0x9d, 0xef, 0xf3, 0xd9, 0xf3, 0x33, 0x4b, 0x76, 0x4b, 0xad, 0xac, 0x32, 0xa3, 0xd9,
	0xb3, 0x51, 0xaa, 0x8a, 0x2b, 0x91, 0x87, 0x7f, 0x43, 0xc4, 0x69, 0x67, 0xf6, 0x6c, 0xe8, 0x81,
	0xc1, 0x6f, 0xa4, 0x77, 0x8c, 0x4f, 0x13, 0xfe, 0x47, 0xc5, 0x8d, 0xa5, 0x9f, 0x93, 0xae, 0xa7,
	0x58, 0x11, 0x4f, 0x79, 0x74, 0xe7, 0xc9, 0x9d, 0xa7, 0x9d, 0x09, 0xf1, 0xd0, 0x29, 0x20, 0xf4,
	0x2b, 0xd2, 0xf2, 0xa7, 0x68, 0x1d, 0xb8, 0xee, 0xde, 0xd6, 0xb0, 0x71, 0x1b, 0x06, 0xab, 0x10,
	0x30, 0x78, 0x43, 0xfa, 0xb5, 0xb9, 0x29, 0x55, 0x61, 0x38, 0xdd, 0x24, 0xeb, 0x53, 0x93, 0x07,
	0x57, 0xf7, 0xb8, 0x64, 0xb7, 0xf6, 0x64, 0xfd, 0xff, 0xed, 0xfe, 0x5a, 0x23, 0x6d, 0x0f, 0x8d,
	0x8f, 0xe8, 0x63, 0xd2, 0xc9, 0x12, 0x96, 0x69, 0x31, 0xe3, 0x3a, 0xf8, 0xb5, 0xb3, 0x64, 0x8c,
	0x67, 0xba, 0x43, 0xee, 0x01, 0xf9, 0x56, 0x19, 0x0b, 0xae, 0x8e, 0x6a, 0x65, 0xc9, 0x2b, 0x38,
	0x05, 0xa2, 0x54, 0xda, 0x62, 0xf6, 0x48, 0x9c, 0xc1, 0x29, 0x10, 0x95, 0x01, 0xb3, 0xbb, 0x35,
	0x71, 0x69, 0x1a, 0xab, 0x32, 0x36, 0x26, 0xda, 0x68, 0x14, 0x70, 0x0a, 0x04, 0x16, 0xa9, 0x55,
	0x13, 0x58, 0xa0, 0xaf, 0x09, 0xb5, 0x71, 0x22, 0x39, 0x2b, 0xb8, 0x7d, 0xaf, 0xf4, 0x3b, 0x76,
	0x25, 0xd5, 0xfb, 0xe8, 0x1e, 0xc6, 0x6c, 0x22, 0x73, 0xea, 0x89, 0x97, 0x80, 0xd3, 0xef, 0xc8,
	0x8e, 0x8f, 0xce, 0x84, 0x49, 0x15, 0x24, 0xcf, 0x33, 0xc8, 0x4f, 0x8a, 0x74, 0x1e, 0xb5, 0x51,
	0xf2, 0x10, 0xe9, 0x71, 0xc3, 0x9e, 0x21, 0x39, 0xb8, 0x20, 0xd4, 0xd7, 0xe2, 0x58, 0x48, 0x51,
	0x4d, 0x5f, 0x55, 0x09, 0x44, 0xd1, 0x5d, 0x42, 0xde, 0xe2, 0x13, 0xab, 0xb4, 0x0c, 0x65, 0xe9,
	0x78, 0xe4, 0x52, 0x4b, 0xd7, 0xdc, 0x40, 0x63, 0x09, 0x7c, 0x6d, 0x82, 0xc2, 0x95, 0x61, 0xf0,
	0xf7, 0x1a, 0xe9, 0xbd, 0xce, 0x0b, 0xa5, 0x45, 0x91, 0xbb, 0xf4, 0x0c, 0xdd, 0x23, 0x0f, 0x61,
	0x16, 0x0c, 0x97, 0x3c, 0xb5, 0x4a, 0xe3, 0xfb, 0x9a, 0x32, 0x4e, 0xeb, 0xc9, 0xd8, 0x16, 0xf9,
	0x79, 0xe0, 0x4e, 0x6b, 0xca, 0x55, 0x60, 0x59, 0x23, 0xe3, 0x84, 0x4b, 0x83, 0xfd, 0x85, 0x0a,
	0x2c, 0x04, 0x27, 0x88, 0xd3, 0x21, 0x01, 0x13, 0x66, 0x63, 0x9d, 0x73, 0xbb, 0xe4, 0xef, 0xfb,
	0xb3, 0x25, 0xf2, 0x0b, 0x64, 0x16, 0xee, 0x4f, 0xc9, 0xe6, 0x22, 0x3e, 0x78, 0xdf, 0x45, 0xef,
	0x7e, 0x1d, 0x1c, 0x9c, 0xe1, 0x75, 0x21, 0x12, 0x67, 0x3e, 0x55, 0x32, 0xf4, 0x8f, 0x88, 0xfc,
	0x2c, 0x20, 0xf4, 0x0b, 0xd2, 0x77, 0x01, 0xf0, 0xe6, 0xac, 0xa8, 0xa6, 0x09, 0x34, 0xdf, 0xb7,
	0xf2, 0x3e, 0xc4, 0x00, 0x78, 0x8a, 0xd8, 0xe0, 0x9f, 0x16, 0x69, 0xf9, 0x5a, 0x7f, 0x7c, 0x3b,
	0x1e, 0x91, 0x96, 0xb1, 0xb1, 0xad, 0x0c, 0x16, 0x77, 0x63, 0x12, 0x4e, 0xf4, 0x1b, 0xd2, 0x09,
	0xc2, 0x2c, 0x09, 0x8b, 0xb3, 0xbd, 0x32, 0xe9, 0xe3, 0xa3, 0x49, 0xdb, 0x03, 0xe3, 0x84, 0xfe,
	0x42, 0x1e, 0x04, 0x45, 0x8a, 0x1d, 0x66, 0xbe, 0x4d, 0x38, 0x9e, 0xdd, 0xbd, 0xdd, 0x15, 0xf1,
	0xf2, 0x1c, 0x4c, 0x68, 0xba, 0x3a, 0x1b, 0x5f, 0x92, 0xbe, 0x2a, 0xb9, 0x8e, 0xad, 0x50, 0x05,
	0x9b, 0xaa, 0x8c, 0x63, 0x41, 0x36, 0x26, 0xbd, 0x06, 0x7d, 0x03, 0xa0, 0x6b, 0x78, 0xaa, 0x55,
	0xf1, 0xbb, 0x4a, 0x98, 0x15, 0x53, 0xce, 0x44, 0x61, 0xb9, 0x9e, 0xc5, 0x32, 0x94, 0x66, 0x3b,
	0x90, 0x17, 0xc0, 0xbd, 0x0e, 0x14, 0x7d, 0x41, 0x1e, 0xab, 0x82, 0xfb, 0xf8, 0x46, 0xe8, 0xfb,
	0x0f, 0xb6, 0x61, 0xf6, 0x77, 0x20, 0xc4, 0xa9, 0x7e, 0xf6, 0xe2, 0xf3, 0x9a, 0x76, 0x0d, 0xad,
	0x57, 0x45, 0xaa, 0x9c, 0x5d, 0x69, 0x35, 0x0d, 0xb3, 0xdf, 0x0f, 0xf8, 0x89, 0xca, 0x5f, 0x02,
	0x0a, 0x55, 0x7c, 0xb0, 0xb2, 0x26, 0xcc, 0xaa, 0xa8, 0x83, 0xd1, 0x34, 0xbb, 0xb6, 0x24, 0x17,
	0xca, 0x2d, 0x44, 0x08, 0xcb, 0x84, 0x8e, 0x88, 0x5f, 0x08, 0x8f, 0x8c, 0x85, 0xa6, 0x07, 0xe4,
	0x51, 0x2d, 0x9a, 0x37, 0x7e, 0xf3, 0x92, 0x9b, 0xa8, 0x8b, 0xb5, 0x69, 0x7e, 0x6e, 0x1e, 0x1c,
	0x1d, 0xb7, 0x9c, 0xc6, 0x9c, 0xe9, 0x0a, 0xd6, 0xc9, 0x6b, 0xee, 0xa3, 0xa6, 0x49, 0x63, 0x3e,
	0x01, 0xca, 0x2b, 0xe0, 0xb6, 0x4a, 0x45, 0xa6, 0x59, 0x22, 0xac, 0x89, 0x7a, 0x18, 0xd6, 0x76,
	0xc0, 0x11, 0x9c, 0xe9, 0x8f, 0x6e, 0x0a, 0xfd, 0xce, 0xe1, 0x5d, 0x61, 0xa2, 0x3e, 0x5e, 0x85,
	0xd1, 0x52, 0x8f, 0x3f, 0x58, 0xca, 0x49, 0x4f, 0x7c, 0xb0, 0xa3, 0x90, 0x8f, 0xdc, 0x67, 0x71,
	0x9e, 0x6b, 0x9e, 0xfb, 0xf6, 0x4a, 0x3e, 0xe3, 0x32, 0xfa, 0xc4, 0xe7, 0x23, 0xf7, 0x0f, 0x17,
	0xd4, 0x89, 0x63, 0xdc, 0x2c, 0xc8, 0x03, 0x96, 0xaa, 0x69, 0xa9, 0xb9, 0x31, 0xae, 0x47, 0x9b,
	0x7e, 0x16, 0xe4, 0xc1, 0xf1, 0x02, 0x44, 0xe3, 0xe7, 0x37, 0x18, 0x6f, 0x05, 0xe3, 0xe7, 0xd7,
	0x8d, 0xf7, 0xfe, 0x5d, 0x23, 0x5d, 0x3f, 0x8f, 0xe7, 0xb0, 0xe1, 0x9c, 0x7e, 0x4f, 0xd6, 0x0f,
	0xb3, 0x8c, 0x46, 0xab, 0xb7, 0xba, 0xff, 0xde, 0x7c, 0xf6, 0xe9, 0x0d, 0x4c, 0xf8, 0x58, 0x80,
	0xf6, 0x27, 0x6e, 0x6f, 0xa7, 0xfd, 0x81, 0xb4, 0x2e, 0xcb, 0x2c, 0xb6, 0xfc, 0xd6, 0xf2, 0x31,
	0xcc, 0xe7, 0x6d, 0xe5, 0x2f, 0xc8, 0xc6, 0x61, 0x59, 0xca, 0xf9, 0xad, 0xd4, 0x47, 0xdf, 0xfe,
	0xba, 0x9f, 0x0b, 0x0b, 0xeb, 0x0e, 0xfc, 0x74, 0x14, 0xa7, 0x69, 0xf5, 0xae, 0x50, 0x7f, 0x8e,
	0xdc, 0x9f, 0xc3, 0xca, 0x2a, 0x3f, 0x89, 0xa3, 0xeb, 0x9f, 0xf8, 0xa4, 0x85, 0xc8, 0xfe, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xe1, 0xf9, 0x92, 0xfd, 0x07, 0x00, 0x00,
}
