// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	securitykubearmorcomv1 "github.com/accuknox/auto-policy-discovery/pkg/discoveredpolicy/api/security.kubearmor.com/v1"
	versioned "github.com/accuknox/auto-policy-discovery/pkg/discoveredpolicy/client/clientset/versioned"
	internalinterfaces "github.com/accuknox/auto-policy-discovery/pkg/discoveredpolicy/client/informers/externalversions/internalinterfaces"
	v1 "github.com/accuknox/auto-policy-discovery/pkg/discoveredpolicy/client/listers/security.kubearmor.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DiscoveredPolicyInformer provides access to a shared informer and lister for
// DiscoveredPolicies.
type DiscoveredPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DiscoveredPolicyLister
}

type discoveredPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDiscoveredPolicyInformer constructs a new informer for DiscoveredPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDiscoveredPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDiscoveredPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDiscoveredPolicyInformer constructs a new informer for DiscoveredPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDiscoveredPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().DiscoveredPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().DiscoveredPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&securitykubearmorcomv1.DiscoveredPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *discoveredPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDiscoveredPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *discoveredPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securitykubearmorcomv1.DiscoveredPolicy{}, f.defaultInformer)
}

func (f *discoveredPolicyInformer) Lister() v1.DiscoveredPolicyLister {
	return v1.NewDiscoveredPolicyLister(f.Informer().GetIndexer())
}
