// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/accuknox/auto-policy-discovery/pkg/discoveredpolicy/client/clientset/versioned/typed/security.kubearmor.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSecurityV1 struct {
	*testing.Fake
}

func (c *FakeSecurityV1) DiscoveredPolicies(namespace string) v1.DiscoveredPolicyInterface {
	return &FakeDiscoveredPolicies{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecurityV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
