// Code generated by lister-gen. DO NOT EDIT.

package v1

// DiscoveredPolicyListerExpansion allows custom methods to be added to
// DiscoveredPolicyLister.
type DiscoveredPolicyListerExpansion interface{}

// DiscoveredPolicyNamespaceListerExpansion allows custom methods to be added to
// DiscoveredPolicyNamespaceLister.
type DiscoveredPolicyNamespaceListerExpansion interface{}
